//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_DS
    {
        public string MA_ChiTietDS { get; set; }
        public string MA_DuongSu { get; set; }
        public string MA_LoaiDS { get; set; }
        public string MA_HoSo { get; set; }
    
        public virtual HOSO_VUAN HOSO_VUAN { get; set; }
        public virtual DUONGSU DUONGSU { get; set; }
        public virtual LOAI_DS LOAI_DS { get; set; }
    }
}
