//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_KHANGCAO
    {
        public string MA_DKC { get; set; }
        public string MA_HoSo { get; set; }
        public string MA_NhanVien { get; set; }
        public System.DateTime Ngay_nhan_don_KC { get; set; }
    
        public virtual HOSO_VUAN HOSO_VUAN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
