//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTRO
    {
        public int MA_HT { get; set; }
        public string HoTen_HT { get; set; }
        public string Cau_Hoi { get; set; }
        public string SDT_HT { get; set; }
        public string Email_HT { get; set; }
        public string MA_TT_HT { get; set; }
    
        public virtual TRANGTHAI_HOTRO TRANGTHAI_HOTRO { get; set; }
    }
}
