//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUA_XX
    {
        public string MA_KetQuaXX { get; set; }
        public Nullable<int> MA_XetXu { get; set; }
        public string KetQua_XX1 { get; set; }
    
        public virtual XETXU XETXU { get; set; }
    }
}
