//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HOSO_VUAN = new HashSet<HOSO_VUAN>();
        }
    
        public string MA_NhanVien { get; set; }
        public string MA_ChucVu { get; set; }
        public string MA_QNSD { get; set; }
        public string MA_PhongBan { get; set; }
        public string HoTen_NV { get; set; }
        public System.DateTime NamSinh_NV { get; set; }
        public bool GioiTinh_NV { get; set; }
        public string QueQuan_NV { get; set; }
        public string CMND_NV { get; set; }
        public string SoDienThoai_NV { get; set; }
        public string MatKhau { get; set; }
        public string Avatar { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSO_VUAN> HOSO_VUAN { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        public virtual QUYEN_NSD QUYEN_NSD { get; set; }
    }
}
