//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_MENU
    {
        public int ID_SUB { get; set; }
        public string Ten_SUB { get; set; }
        public string Controller_SUB { get; set; }
        public string Action_SUB { get; set; }
        public string MA_QNSD { get; set; }
        public Nullable<int> ID_Main { get; set; }
    
        public virtual MAIN_MENU MAIN_MENU { get; set; }
        public virtual QUYEN_NSD QUYEN_NSD { get; set; }
    }
}
