//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NienLuan2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XETXU
    {
        public int STT_XX { get; set; }
        public string Ngay_XetXu { get; set; }
        public int Lan_XetXu { get; set; }
        public string MA_DiaDiem { get; set; }
        public string MA_HoSo { get; set; }
        public string MA_DuongSu { get; set; }
        public string KetQua_XX { get; set; }
    
        public virtual DIADIEM_XX DIADIEM_XX { get; set; }
        public virtual DUONGSU DUONGSU { get; set; }
        public virtual HOSO_VUAN HOSO_VUAN { get; set; }
    }
}
